components:
  schemas:
    EventInfo:
      description: Model representing GHGA-internal event info
      properties:
        headers:
          additionalProperties:
            type: string
          description: Any headers for the event. Must at least include correlation
            ID.
          title: Headers
          type: object
        key:
          description: The key of the event.
          title: Key
          type: string
        payload:
          description: The payload for the event.
          title: Payload
          type: object
        timestamp:
          description: The timestamp of the event.
          format: date-time
          title: Timestamp
          type: string
        topic:
          description: The name of the original topic the event was located in.
          title: Topic
          type: string
        type_:
          description: The 'type' given to the original event.
          title: Type
          type: string
      required:
      - topic
      - type_
      - payload
      - key
      - headers
      title: EventInfo
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  description: A service to manage the dead letter queue for Kafka events
  title: DLQ Service
  version: 1.0.0
openapi: 3.1.0
paths:
  /health:
    get:
      description: Used to test if this service is alive
      operationId: health_health_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: health
  /{service}/{topic}:
    delete:
      description: Process the next event in the topic, optionally publishing the
        supplied event
      operationId: discard_event__service___topic__delete
      parameters:
      - in: path
        name: service
        required: true
        schema:
          title: Service
          type: string
      - in: path
        name: topic
        required: true
        schema:
          title: Topic
          type: string
      responses:
        '204':
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Discard Event
    get:
      description: 'Return the next events in the topic.


        This is a preview of the events and does not impact event ordering within
        the DLQ.'
      operationId: get_events__service___topic__get
      parameters:
      - in: path
        name: service
        required: true
        schema:
          title: Service
          type: string
      - in: path
        name: topic
        required: true
        schema:
          title: Topic
          type: string
      - in: query
        name: skip
        required: false
        schema:
          default: 0
          title: Skip
          type: integer
      - in: query
        name: limit
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Limit
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/EventInfo'
                title: Response Get Events  Service   Topic  Get
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Return the next events in the topic
    post:
      description: Process the next event in the topic, optionally publishing the
        supplied event
      operationId: process_event__service___topic__post
      parameters:
      - in: path
        name: service
        required: true
        schema:
          title: Service
          type: string
      - in: path
        name: topic
        required: true
        schema:
          title: Topic
          type: string
      - in: query
        name: dry_run
        required: false
        schema:
          default: false
          title: Dry Run
          type: boolean
      requestBody:
        content:
          application/json:
            schema:
              anyOf:
              - $ref: '#/components/schemas/EventInfo'
              - type: 'null'
              title: Override
      responses:
        '204':
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Process Event
servers:
- url: ''
