services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        # [Choice] Install Node.js
        INSTALL_NODE: "false"
        NODE_VERSION: "lts/*"
        # Please adapt to package name:
        PACKAGE_NAME: "dlqs"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    init: true

    # Makes testcontainers work on linux based hosts
    extra_hosts:
      - host.docker.internal:host-gateway

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode

    # define environment variables
    environment:
      # Please adapt to package name:
      DLQS_CONFIG_YAML: /workspace/.devcontainer/.dev_config.yaml


volumes:
  s3_fs: {}
  mongo_fs: {}
