services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        # [Choice] Install Node.js
        INSTALL_NODE: "false"
        NODE_VERSION: "lts/*"
        # Please adapt to package name:
        PACKAGE_NAME: "dlqs"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    init: true

    # Makes testcontainers work on linux based hosts
    extra_hosts:
      - host.docker.internal:host-gateway

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode

    # define environment variables
    environment:
      # Please adapt to package name:
      DLQS_CONFIG_YAML: /workspace/.devcontainer/.dev_config.yaml

  mongodb:
    image: mongo:7.0.12
    restart: unless-stopped
    volumes:
      - mongo_fs:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.2
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-server:7.6.2
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1


volumes:
  mongo_fs: {}
