[project]
name = "dlqs"
version = "4.0.0"
description = "DLQ Service - a service to manage the dead letter queue for Kafka events"
dependencies = [
    "typer >= 0.19",
    "ghga-service-commons[api] >= 7.0",
    "hexkit[akafka,mongodb] >= 8.0",
]

[project.urls]
Repository = "https://github.com/ghga-de/dlq-service"

[project.scripts]
dlqs = "dlqs.__main__:cli"
