[project]
name = "dlqs"
version = "3.0.0"
description = "DLQ Service - a service to manage the dead letter queue for Kafka events"
dependencies = [
    "typer >= 0.15",
    "ghga-service-commons[api] >= 5",
    "hexkit[akafka,mongodb] >= 6",
]

[project.urls]
Repository = "https://github.com/ghga-de/dlq-service"

[project.scripts]
dlqs = "dlqs.__main__:cli"
