[project]
name = "dlqs"
version = "1.0.0"
description = "DLQ Service - a service to manage the dead letter queue for Kafka events"
dependencies = [
    "typer >= 0.12",
    "ghga-service-commons[api] >= 3.3",
    "hexkit[akafka,mongodb] >= 4",
]

[project.urls]
Repository = "https://github.com/ghga-de/dlq-service"

[project.scripts]
dlqs = "dlqs.__main__:cli"
