[project]
name = "dlqs"
version = "3.0.1"
description = "DLQ Service - a service to manage the dead letter queue for Kafka events"
dependencies = [
    "typer >= 0.19",
    "ghga-service-commons[api] >= 5.1",
    "hexkit[akafka,mongodb] >= 7.1",
]

[project.urls]
Repository = "https://github.com/ghga-de/dlq-service"

[project.scripts]
dlqs = "dlqs.__main__:cli"
