[project]
name = "dlqs"
version = "2.0.3"
description = "DLQ Service - a service to manage the dead letter queue for Kafka events"
dependencies = [
    "typer >= 0.15",
    "ghga-service-commons[api] >= 4.1",
    "hexkit[akafka,mongodb] >= 5.4.1",
]

[project.urls]
Repository = "https://github.com/ghga-de/dlq-service"

[project.scripts]
dlqs = "dlqs.__main__:cli"
